// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa6KOEeWpKKCon0UbC8JPc1sQAadFAVSQ',
    appId: '1:973675671034:web:1d6d460ceb39fa3a78c843',
    messagingSenderId: '973675671034',
    projectId: 'flutter-projects-b6960',
    authDomain: 'flutter-projects-b6960.firebaseapp.com',
    storageBucket: 'flutter-projects-b6960.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAKhlbfAPNDQYKQH0XFKApOGroicbycos',
    appId: '1:973675671034:android:d1b77682fb1fe48578c843',
    messagingSenderId: '973675671034',
    projectId: 'flutter-projects-b6960',
    storageBucket: 'flutter-projects-b6960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfbHvYEwH6jsGN-1uFzZ4aHuYDjb16h1k',
    appId: '1:973675671034:ios:719a4d1908b19bf278c843',
    messagingSenderId: '973675671034',
    projectId: 'flutter-projects-b6960',
    storageBucket: 'flutter-projects-b6960.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfbHvYEwH6jsGN-1uFzZ4aHuYDjb16h1k',
    appId: '1:973675671034:ios:9271f39aaae1bd7978c843',
    messagingSenderId: '973675671034',
    projectId: 'flutter-projects-b6960',
    storageBucket: 'flutter-projects-b6960.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
